//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maintenance.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Maintenance.Core.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة الحساب.
        /// </summary>
        public static string AccountStatus {
            get {
                return ResourceManager.GetString("AccountStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العمليات.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفعيل.
        /// </summary>
        public static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال.
        /// </summary>
        public static string Activated {
            get {
                return ResourceManager.GetString("Activated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قم بإضافة قطع سند الاستلام.
        /// </summary>
        public static string AddItemsMsg {
            get {
                return ResourceManager.GetString("AddItemsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدير النظام.
        /// </summary>
        public static string Administrator {
            get {
                return ResourceManager.GetString("Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظام الصيانة.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قبول.
        /// </summary>
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سيئ.
        /// </summary>
        public static string Bad {
            get {
                return ResourceManager.GetString("Bad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الباركود.
        /// </summary>
        public static string Barcode {
            get {
                return ResourceManager.GetString("Barcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ممتاز.
        /// </summary>
        public static string Best {
            get {
                return ResourceManager.GetString("Best", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفرع.
        /// </summary>
        public static string Branch {
            get {
                return ResourceManager.GetString("Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفروع.
        /// </summary>
        public static string Branches {
            get {
                return ResourceManager.GetString("Branches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم هاتف للفرع.
        /// </summary>
        public static string BranchPhoneNumber {
            get {
                return ResourceManager.GetString("BranchPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أرقام هواتف الفرع.
        /// </summary>
        public static string BranchPhoneNumbers {
            get {
                return ResourceManager.GetString("BranchPhoneNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إلغاء.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغيير كلمة المرور.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فحص القطعة.
        /// </summary>
        public static string CheckItem {
            get {
                return ResourceManager.GetString("CheckItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المبلغ المحصل.
        /// </summary>
        public static string CollectedAmount {
            get {
                return ResourceManager.GetString("CollectedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التحصيل.
        /// </summary>
        public static string CollectingMoney {
            get {
                return ResourceManager.GetString("CollectingMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ التحصيل.
        /// </summary>
        public static string CollectionDate {
            get {
                return ResourceManager.GetString("CollectionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اللون.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الألوان.
        /// </summary>
        public static string Colors {
            get {
                return ResourceManager.GetString("Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشركات.
        /// </summary>
        public static string Compaines {
            get {
                return ResourceManager.GetString("Compaines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشركة.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شركة.
        /// </summary>
        public static string CompanyWithoutDef {
            get {
                return ResourceManager.GetString("CompanyWithoutDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إنهاء الصيانة.
        /// </summary>
        public static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مكتمل.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التكلفة التي تم إبلاغ العميل بها.
        /// </summary>
        public static string CostNotifiedToTheCustomer {
            get {
                return ResourceManager.GetString("CostNotifiedToTheCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إنشاء جديد.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إنشاء {0}.
        /// </summary>
        public static string CreateTitle {
            get {
                return ResourceManager.GetString("CreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الإضافة.
        /// </summary>
        public static string CreationDate {
            get {
                return ResourceManager.GetString("CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العميل.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موافقة العميل.
        /// </summary>
        public static string CustomerApproved {
            get {
                return ResourceManager.GetString("CustomerApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم العميل.
        /// </summary>
        public static string CustomerFullName {
            get {
                return ResourceManager.GetString("CustomerFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم هاتف العميل.
        /// </summary>
        public static string CustomerPhoneNumber {
            get {
                return ResourceManager.GetString("CustomerPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقييم العميل.
        /// </summary>
        public static string CustomerRate {
            get {
                return ResourceManager.GetString("CustomerRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رفض العميل.
        /// </summary>
        public static string CustomerRefused {
            get {
                return ResourceManager.GetString("CustomerRefused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العملاء.
        /// </summary>
        public static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عميل.
        /// </summary>
        public static string CustomerWithoutDef {
            get {
                return ResourceManager.GetString("CustomerWithoutDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لوحة التحكم.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التاريخ.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعطيل.
        /// </summary>
        public static string DeActivate {
            get {
                return ResourceManager.GetString("DeActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير فعال.
        /// </summary>
        public static string DeActivated {
            get {
                return ResourceManager.GetString("DeActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل أنت متأكد من استمرار العملية ؟.
        /// </summary>
        public static string DeleteConfirmationForModal {
            get {
                return ResourceManager.GetString("DeleteConfirmationForModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسليم الكل.
        /// </summary>
        public static string DeliverAll {
            get {
                return ResourceManager.GetString("DeliverAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم التسليم.
        /// </summary>
        public static string Delivered {
            get {
                return ResourceManager.GetString("Delivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقرير القطع المسلمة.
        /// </summary>
        public static string DeliveredItemsReport {
            get {
                return ResourceManager.GetString("DeliveredItemsReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التسليم.
        /// </summary>
        public static string Delivery {
            get {
                return ResourceManager.GetString("Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ التسليم.
        /// </summary>
        public static string DeliveryDate {
            get {
                return ResourceManager.GetString("DeliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصف.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التفاصيل.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل {0}.
        /// </summary>
        public static string EditTitle {
            get {
                return ResourceManager.GetString("EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني موجود مسبقاً.
        /// </summary>
        public static string EmailAlreadyExists {
            get {
                return ResourceManager.GetString("EmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل {0}.
        /// </summary>
        public static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل بياناتك لتسجيل الدخول إلى حسابك:.
        /// </summary>
        public static string EnterLoginDetails {
            get {
                return ResourceManager.GetString("EnterLoginDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدخال التكلفة.
        /// </summary>
        public static string EnterMaintenanceCost {
            get {
                return ResourceManager.GetString("EnterMaintenanceCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنصر موجود من قبل.
        /// </summary>
        public static string EntityAlreadyExists {
            get {
                return ResourceManager.GetString("EntityAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنصر غير موجود.
        /// </summary>
        public static string EntityNotFound {
            get {
                return ResourceManager.GetString("EntityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سابق.
        /// </summary>
        public static string Exists {
            get {
                return ResourceManager.GetString("Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عميل سابق / جديد.
        /// </summary>
        public static string ExistsOrNewCustomer {
            get {
                return ResourceManager.GetString("ExistsOrNewCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدخال البيانات المطلوبة.
        /// </summary>
        public static string FillRequiredData {
            get {
                return ResourceManager.GetString("FillRequiredData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإسم الكامل.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جيد.
        /// </summary>
        public static string Good {
            get {
                return ResourceManager.GetString("Good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سند استلام القطع.
        /// </summary>
        public static string HandReceipt {
            get {
                return ResourceManager.GetString("HandReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قطعة سند الاستلام.
        /// </summary>
        public static string HandReceiptItem {
            get {
                return ResourceManager.GetString("HandReceiptItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قطع سند الاستلام.
        /// </summary>
        public static string HandReceiptItems {
            get {
                return ResourceManager.GetString("HandReceiptItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم سند الاستلام.
        /// </summary>
        public static string HandReceiptNumber {
            get {
                return ResourceManager.GetString("HandReceiptNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سندات استلام القطع.
        /// </summary>
        public static string HandReceipts {
            get {
                return ResourceManager.GetString("HandReceipts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصورة.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض بيانات {0} في النظام .
        /// </summary>
        public static string IndexSubTitle {
            get {
                return ResourceManager.GetString("IndexSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إبلاغ العميل بالتكلفة.
        /// </summary>
        public static string InformCustomerOfTheCost {
            get {
                return ResourceManager.GetString("InformCustomerOfTheCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني غير صالح.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البيانات المدخلة غير صحيحة.
        /// </summary>
        public static string InvalidInput {
            get {
                return ResourceManager.GetString("InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف غير صالح.
        /// </summary>
        public static string InvalidPhone {
            get {
                return ResourceManager.GetString("InvalidPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القطعة.
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تفعيل العنصر بنجاح.
        /// </summary>
        public static string ItemActivatedSuccessfully {
            get {
                return ResourceManager.GetString("ItemActivatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أرقام القطع.
        /// </summary>
        public static string ItemBarcodes {
            get {
                return ResourceManager.GetString("ItemBarcodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إنشاء العنصر بنجاح.
        /// </summary>
        public static string ItemCreatedSuccessfully {
            get {
                return ResourceManager.GetString("ItemCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إلغاء تفعيل العنصر بنجاح.
        /// </summary>
        public static string ItemDeActivatedSuccessfully {
            get {
                return ResourceManager.GetString("ItemDeActivatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف العنصر بنجاح.
        /// </summary>
        public static string ItemDeletedSuccessfully {
            get {
                return ResourceManager.GetString("ItemDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القطع.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعديل العنصر بنجاح.
        /// </summary>
        public static string ItemUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("ItemUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قطعة.
        /// </summary>
        public static string ItemWithoutDef {
            get {
                return ResourceManager.GetString("ItemWithoutDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rtl.
        /// </summary>
        public static string LayoutDir {
            get {
                return ResourceManager.GetString("LayoutDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الدخول.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الدخول إلى نظام الصيانة.
        /// </summary>
        public static string LoginToMaintenanceApp {
            get {
                return ResourceManager.GetString("LoginToMaintenanceApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تكلفة الصيانة.
        /// </summary>
        public static string MaintenanceCost {
            get {
                return ResourceManager.GetString("MaintenanceCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قطع الصيانة.
        /// </summary>
        public static string MaintenanceItems {
            get {
                return ResourceManager.GetString("MaintenanceItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدير الصيانة.
        /// </summary>
        public static string MaintenanceManager {
            get {
                return ResourceManager.GetString("MaintenanceManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سبب تعليق الصيانة.
        /// </summary>
        public static string MaintenanceSuspensionReason {
            get {
                return ResourceManager.GetString("MaintenanceSuspensionReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فني الصيانة.
        /// </summary>
        public static string MaintenanceTechnician {
            get {
                return ResourceManager.GetString("MaintenanceTechnician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإسم.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جديد.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جديدة / معادة.
        /// </summary>
        public static string NewOrReturned {
            get {
                return ResourceManager.GetString("NewOrReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور الجديدة.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جديدة.
        /// </summary>
        public static string NewReceiptItem {
            get {
                return ResourceManager.GetString("NewReceiptItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المبلغ المدخل غير مسموح به.
        /// </summary>
        public static string NotAllowedAmount {
            get {
                return ResourceManager.GetString("NotAllowedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقرير القطع التي تم صيانتها (غير مستلمة).
        /// </summary>
        public static string NotDeliveredItemsReport {
            get {
                return ResourceManager.GetString("NotDeliveredItemsReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملاحظات.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إبلاغ العميل بانتهاء الصيانة.
        /// </summary>
        public static string NotifyCustomerOfMaintenanceEnd {
            get {
                return ResourceManager.GetString("NotifyCustomerOfMaintenanceEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يتطلب إبلاغ العميل بالتكلفة؟.
        /// </summary>
        public static string NotifyCustomerOfTheCost {
            get {
                return ResourceManager.GetString("NotifyCustomerOfTheCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقرير القطع التي لم يتم صيانتها.
        /// </summary>
        public static string NotMaintainedItemsReport {
            get {
                return ResourceManager.GetString("NotMaintainedItemsReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ليس لديك صلاحية لتنفيذ العملية.
        /// </summary>
        public static string NoValidity {
            get {
                return ResourceManager.GetString("NoValidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور القديمة.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل تنفيذ العملية.
        /// </summary>
        public static string OperationFailed {
            get {
                return ResourceManager.GetString("OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تحديث كلمة المرور بنجاح.
        /// </summary>
        public static string PasswordUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("PasswordUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أرقام الهواتف.
        /// </summary>
        public static string PhoneNumbers {
            get {
                return ResourceManager.GetString("PhoneNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طباعة.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملف الشخصي.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سبب رفض العميل للصيانة.
        /// </summary>
        public static string ReasonForRefusingMaintenance {
            get {
                return ResourceManager.GetString("ReasonForRefusingMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقرير القطع المستلمة.
        /// </summary>
        public static string ReceiptItemsReport {
            get {
                return ResourceManager.GetString("ReceiptItemsReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رفض.
        /// </summary>
        public static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الإسترجاع.
        /// </summary>
        public static string RemovedFromMaintained {
            get {
                return ResourceManager.GetString("RemovedFromMaintained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استرجاع.
        /// </summary>
        public static string RemoveFromMaintained {
            get {
                return ResourceManager.GetString("RemoveFromMaintained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سبب الإسترجاع.
        /// </summary>
        public static string RemoveFromMaintainedReason {
            get {
                return ResourceManager.GetString("RemoveFromMaintainedReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التقارير.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حقل {0} مطلوب.
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معادة.
        /// </summary>
        public static string Returned {
            get {
                return ResourceManager.GetString("Returned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقرير القطع المعادة.
        /// </summary>
        public static string ReturnedItemsReport {
            get {
                return ResourceManager.GetString("ReturnedItemsReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سند القطع المعادة.
        /// </summary>
        public static string ReturnHandReceipt {
            get {
                return ResourceManager.GetString("ReturnHandReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قطعة معادة.
        /// </summary>
        public static string ReturnHandReceiptItem {
            get {
                return ResourceManager.GetString("ReturnHandReceiptItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القطع المعادة.
        /// </summary>
        public static string ReturnHandReceiptItems {
            get {
                return ResourceManager.GetString("ReturnHandReceiptItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سندات القطع المعادة.
        /// </summary>
        public static string ReturnHandReceipts {
            get {
                return ResourceManager.GetString("ReturnHandReceipts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سبب الإرجاع.
        /// </summary>
        public static string ReturnReason {
            get {
                return ResourceManager.GetString("ReturnReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ر.س.
        /// </summary>
        public static string SAR {
            get {
                return ResourceManager.GetString("SAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسح الباركود.
        /// </summary>
        public static string ScanBarcode {
            get {
                return ResourceManager.GetString("ScanBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بحث....
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر {0}.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر العملية.
        /// </summary>
        public static string SelectAction {
            get {
                return ResourceManager.GetString("SelectAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الخروج.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التكلفة المحددة.
        /// </summary>
        public static string SpecifiedCost {
            get {
                return ResourceManager.GetString("SpecifiedCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإحصائيات.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحالة.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلق.
        /// </summary>
        public static string Suspended {
            get {
                return ResourceManager.GetString("Suspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعليق الصيانة.
        /// </summary>
        public static string Suspension {
            get {
                return ResourceManager.GetString("Suspension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إلى.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المبلغ الإجمالي المحصل.
        /// </summary>
        public static string TotalCollectedAmount {
            get {
                return ResourceManager.GetString("TotalCollectedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مستعجل.
        /// </summary>
        public static string Urgent {
            get {
                return ResourceManager.GetString("Urgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقرير القطع المستعجلة.
        /// </summary>
        public static string UrgentItemsReport {
            get {
                return ResourceManager.GetString("UrgentItemsReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مستخدم.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدمين.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع المستخدم.
        /// </summary>
        public static string UserType {
            get {
                return ResourceManager.GetString("UserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحذير.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد أيام الضمان.
        /// </summary>
        public static string WarrantyDaysNumber {
            get {
                return ResourceManager.GetString("WarrantyDaysNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الضمان منتهي.
        /// </summary>
        public static string WarrantyExpired {
            get {
                return ResourceManager.GetString("WarrantyExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم تبدأ فترة الضمان.
        /// </summary>
        public static string WarrantyPeriodNotStarted {
            get {
                return ResourceManager.GetString("WarrantyPeriodNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الضمان ساري.
        /// </summary>
        public static string WarrantyValid {
            get {
                return ResourceManager.GetString("WarrantyValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرحباً.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نعم.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
